import type { LegalSection } from '@/lib/legal'

export const introSections: LegalSection[] = [
  {
    title: null,
    body: (
      <p>
        By accessing or using Atrox (&ldquo;the Service&rdquo;), you agree to be
        bound by these Terms of Service. If you do not agree, do not use the
        Service.
      </p>
    ),
  },
  {
    title: '1. Age Requirement',
    body: (
      <p>
        You must be at least 18 years old to use Atrox. By using the Service,
        you represent that you are of legal age in your jurisdiction.
      </p>
    ),
  },
  {
    title: '2. AI-Generated Content Disclosure',
    body: (
      <>
        <p>
          All episodes and fiction on Atrox are generated by an AI character
          (Vesper Black) powered by Anthropic&apos;s Claude API. In accordance
          with the EU AI Act (Article 50), we clearly disclose that you are
          interacting with AI-generated content.
        </p>
        <p>
          AI-generated works may have limited or no copyright protection under
          applicable law. Atrox asserts contractual rights — not copyright
          ownership — over the generated content.
        </p>
      </>
    ),
  },
  {
    title: '3. Intellectual Property and License',
    body: (
      <>
        <p>
          The Atrox platform, brand, trademarks, and original character concepts
          (including Vesper Black) are owned by Atrox. Atrox grants you a
          personal, non-commercial, revocable license to read episodes through
          the Service.
        </p>
        <ul>
          <li>You may not redistribute, republish, or sell episodes</li>
          <li>You may not use the content to train other AI models</li>
          <li>
            Reader comments you submit grant Atrox a non-exclusive, worldwide,
            royalty-free license to use them as input for future episode
            generation
          </li>
        </ul>
      </>
    ),
  },
]
