import type { Metadata } from 'next'

interface EpisodePageProps {
  params: Promise<{ episodeNumber: string }>
}

export async function generateMetadata({
  params,
}: EpisodePageProps): Promise<Metadata> {
  const { episodeNumber } = await params
  return {
    title: `Episode ${episodeNumber} — Atrox`,
    description: `Episode ${episodeNumber} by Vesper Black.`,
  }
}

export default async function EpisodePage({ params }: EpisodePageProps) {
  const { episodeNumber } = await params
  const num = Number(episodeNumber)

  return (
    <article className="mx-auto max-w-xl px-6 py-20">
      <header className="mb-12 animate-fade-up">
        <p className="text-xs uppercase tracking-[0.3em] text-gold-muted mb-4">
          Episode {String(num).padStart(2, '0')}
        </p>
        <h1 className="font-display text-4xl md:text-5xl leading-tight tracking-tight italic">
          The Invitation
        </h1>
        <div className="mt-4 flex items-center gap-3 text-xs text-fg-muted tracking-wider">
          <span>by Vesper Black</span>
          <span className="text-border">&middot;</span>
          <time>April 7, 2026</time>
        </div>
      </header>

      <div className="animate-fade-up stagger-2 prose-atrox space-y-6 text-lg leading-[1.9] text-fg/90">
        <p className="first-letter:text-5xl first-letter:font-display first-letter:text-gold first-letter:float-left first-letter:mr-2 first-letter:mt-1">
          The letter arrived at dusk, as all dangerous things do. It bore no
          seal, no signature — only an address written in ink the color of dried
          blood.
        </p>
        <p>She read it once, then burned it. The words stayed anyway.</p>
        <p>
          There are invitations you cannot refuse. Not because they compel — but
          because the part of you that should say no has been waiting for
          exactly this.
        </p>
        <p className="text-fg-muted italic">
          Episode content will be loaded from the API once connected.
        </p>
      </div>

      <footer className="mt-16 pt-8 border-t border-border animate-fade-up stagger-3">
        <p className="text-xs text-fg-muted/60 tracking-wider text-center">
          AI-generated by Vesper Black &middot; Powered by Claude
        </p>
      </footer>
    </article>
  )
}
