import type { Metadata } from 'next'
import { notFound, redirect } from 'next/navigation'
import {
  db,
  getCharacterBySlug,
  getActiveArc,
  getEpisodeByNumber,
  getEffectiveTier,
} from '@atrox/db'
import { getCurrentTier } from '@/lib/current-tier'
import { EpisodeBody } from '@/components/episode-body'
import { TIER_ORDER } from '@atrox/types'

interface EpisodePageProps {
  params: Promise<{ episodeNumber: string }>
}

export async function generateMetadata({
  params,
}: EpisodePageProps): Promise<Metadata> {
  const { episodeNumber } = await params
  return {
    title: `Episode ${episodeNumber} — Atrox`,
    description: `Episode ${episodeNumber} by Vesper Black.`,
  }
}

export const revalidate = 60

export default async function EpisodePage({ params }: EpisodePageProps) {
  const { episodeNumber } = await params
  const num = Number(episodeNumber)
  if (!Number.isInteger(num) || num < 1) notFound()

  const character = await getCharacterBySlug(db, 'vesper-black')
  if (!character) notFound()

  const arc = await getActiveArc(db, character.id)
  if (!arc) notFound()

  const episode = await getEpisodeByNumber(db, arc.id, num)
  if (!episode) notFound()

  // Tier gate — uses effective tier (respects 3-day early access window)
  const userTier = await getCurrentTier()
  const required = getEffectiveTier(episode)
  if (TIER_ORDER[userTier] < TIER_ORDER[required]) {
    redirect('/pricing?required=' + required)
  }

  return (
    <article className="mx-auto max-w-xl px-6 py-20">
      <header className="mb-12 animate-fade-up">
        <p className="text-xs uppercase tracking-[0.3em] text-gold-muted mb-4">
          Episode {String(episode.episodeNumber).padStart(2, '0')}
        </p>
        <h1 className="font-display text-4xl md:text-5xl leading-tight tracking-tight italic">
          {episode.title ?? 'Untitled'}
        </h1>
        <div className="mt-4 flex items-center gap-3 text-xs text-fg-muted tracking-wider">
          <span>by {character.name}</span>
          {episode.publishedAt && (
            <>
              <span className="text-border">&middot;</span>
              <time>{episode.publishedAt.toISOString().slice(0, 10)}</time>
            </>
          )}
        </div>
      </header>

      <div className="animate-fade-up stagger-2">
        <EpisodeBody body={episode.body} />
      </div>

      <footer className="mt-16 pt-8 border-t border-border animate-fade-up stagger-3">
        <p className="text-xs text-fg-muted/60 tracking-wider text-center">
          AI-generated by {character.name} &middot; Powered by Claude
        </p>
      </footer>
    </article>
  )
}
