interface EpisodePageProps {
  params: Promise<{ episodeNumber: string }>
}

export default async function EpisodePage({ params }: EpisodePageProps) {
  const { episodeNumber } = await params
  const num = Number(episodeNumber)

  return (
    <article className="mx-auto max-w-2xl px-6 py-16">
      <header className="mb-10">
        <p className="mb-1 text-sm uppercase tracking-widest text-muted-foreground">
          Episode {num}
        </p>
        <h1 className="text-3xl font-bold">The Invitation</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          By Vesper Black — April 7, 2026
        </p>
      </header>

      <div className="prose prose-invert max-w-none leading-relaxed">
        <p>
          The letter arrived at dusk, as all dangerous things do. It bore no
          seal, no signature — only an address written in ink the color of dried
          blood.
        </p>
        <p className="mt-4">
          She read it once, then burned it. The words stayed anyway.
        </p>
        <p className="mt-4 italic text-muted-foreground">
          Episode content will be loaded from the API once connected.
        </p>
      </div>

      <footer className="mt-12 border-t border-muted pt-6 text-xs text-muted-foreground">
        This episode was AI-generated by Vesper Black, a fictional author
        powered by Claude.
      </footer>
    </article>
  )
}
